import type { HouseKey } from "./houses";
import type { MaterialId } from "./materials";

export type LevelCost = Partial<Record<MaterialId, number>>;

export const COSTS: Record<HouseKey, Record<number, LevelCost>> = {
    "Dairy Barn": {
        1: {
            Coin: 500_000,
            Lumber: 75,
            Milk: 1_500,
            "Cheese Brush": 6
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            Milk: 3_000,
            "Verdant Milk": 3_000,
            "Cheese Brush": 9,
            "Verdant Brush": 9
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Verdant Milk": 6_000,
            "Azure Milk": 6_000,
            "Verdant Brush": 12,
            "Azure Brush": 12
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Azure Milk": 12_000,
            "Burble Milk": 12_000,
            "Azure Brush": 15,
            "Burble Brush": 15,
            "Milking Tea": 1_000
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Burble Milk": 24_000,
            "Crimson Milk": 24_000,
            "Burble Brush": 18,
            "Crimson Brush": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Crimson Milk": 48_000,
            "Rainbow Milk": 48_000,
            "Crimson Brush": 21,
            "Rainbow Brush": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Rainbow Milk": 96_000,
            "Holy Milk": 96_000,
            "Rainbow Brush": 24,
            "Holy Brush": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Holy Milk": 240_000,
            "Holy Brush": 60,
            "Super Milking Tea": 2_000,
        },
    },
    Garden: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            Egg: 500,
            Wheat: 500,
            Cotton: 750,
            "Cheese Shears": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            Egg: 1_000,
            Blueberry: 1_000,
            Wheat: 1_000,
            Apple: 500,
            Cotton: 1_500,
            Flax: 1_500,
            "Cheese Shears": 9,
            "Verdant Shears": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            Blueberry: 2_000,
            Blackberry: 2_000,
            Apple: 1_000,
            Orange: 1_000,
            Flax: 6_000,
            "Verdant Shears": 12,
            "Azure Shears": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            Blackberry: 4_000,
            Strawberry: 4_000,
            Orange: 2_000,
            Plum: 2_000,
            Flax: 6_000,
            "Bamboo Branch": 6_000,
            "Azure Shears": 15,
            "Burble Shears": 15,
            "Foraging Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            Strawberry: 8_000,
            Mooberry: 8_000,
            Plum: 4_000,
            Peach: 4_000,
            "Bamboo Branch": 24_000,
            "Burble Shears": 18,
            "Crimson Shears": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            Mooberry: 16_000,
            Marsberry: 16_000,
            Peach: 8_000,
            "Dragon Fruit": 8_000,
            "Bamboo Branch": 24_000,
            Cocoon: 24_000,
            "Crimson Shears": 21,
            "Rainbow Shears": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            Marsberry: 32_000,
            Spaceberry: 32_000,
            "Dragon Fruit": 16_000,
            "Star Fruit": 16_000,
            Cocoon: 48_000,
            "Radiant Fiber": 48_000,
            "Rainbow Shears": 24,
            "Holy Shears": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            Spaceberry: 80_000,
            "Star Fruit": 40_000,
            "Radiant Fiber": 120_000,
            "Holy Shears": 60,
            "Super Foraging Tea": 2_000,
        },
    },
    "Log Shed": {
        1: {
            Coin: 500_000,
            Lumber: 75,
            Log: 1_500,
            "Cheese Hatchet": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            Log: 3_000,
            "Birch Log": 3_000,
            "Cheese Hatchet": 9,
            "Verdant Hatchet": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Birch Log": 6_000,
            "Cedar Log": 6_000,
            "Verdant Hatchet": 12,
            "Azure Hatchet": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Cedar Log": 12_000,
            "Purpleheart Log": 12_000,
            "Azure Hatchet": 15,
            "Burble Hatchet": 15,
            "Woodcutting Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Purpleheart Log": 24_000,
            "Ginkgo Log": 24_000,
            "Burble Hatchet": 18,
            "Crimson Hatchet": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Ginkgo Log": 48_000,
            "Redwood Log": 48_000,
            "Crimson Hatchet": 21,
            "Rainbow Hatchet": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Redwood Log": 96_000,
            "Arcane Log": 96_000,
            "Rainbow Hatchet": 24,
            "Holy Hatchet": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Arcane Log": 240_000,
            "Holy Hatchet": 60,
            "Super Woodcutting Tea": 2_000,
        },
    },
    Forge: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            Cheese: 375,
            "Cheese Hammer": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            Cheese: 750,
            "Verdant Cheese": 750,
            "Cheese Hammer": 9,
            "Verdant Hammer": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Verdant Cheese": 1_500,
            "Azure Cheese": 1_500,
            "Verdant Hammer": 12,
            "Azure Hammer": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Azure Cheese": 3_000,
            "Burble Cheese": 3_000,
            "Azure Hammer": 15,
            "Burble Hammer": 15,
            "Cheesesmithing Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Burble Cheese": 6_000,
            "Crimson Cheese": 6_000,
            "Burble Hammer": 18,
            "Crimson Hammer": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Crimson Cheese": 12_000,
            "Rainbow Cheese": 12_000,
            "Crimson Hammer": 21,
            "Rainbow Hammer": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Rainbow Cheese": 24_000,
            "Holy Cheese": 24_000,
            "Rainbow Hammer": 24,
            "Holy Hammer": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Holy Cheese": 60_000,
            "Holy Hammer": 60,
            "Super Cheesesmithing Tea": 2_000,
        },
    },
    Workshop: {
        1: {
            Coin: 500_000,
            Lumber: 450,
            "Cheese Chisel": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 900,
            "Birch Lumber": 900,
            "Cheese Chisel": 9,
            "Verdant Chisel": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 1_800,
            "Cedar Lumber": 1_800,
            "Verdant Chisel": 12,
            "Azure Chisel": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 3_600,
            "Purpleheart Lumber": 3_600,
            "Azure Chisel": 15,
            "Burble Chisel": 15,
            "Crafting Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 7_200,
            "Ginkgo Lumber": 7_200,
            "Burble Chisel": 18,
            "Crimson Chisel": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 14_400,
            "Redwood Lumber": 14_400,
            "Crimson Chisel": 21,
            "Rainbow Chisel": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 28_800,
            "Arcane Lumber": 28_800,
            "Rainbow Chisel": 24,
            "Holy Chisel": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 72_000,
            "Holy Chisel": 60,
            "Super Crafting Tea": 2_000,
        },
    },
    "Sewing Parlor": {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Rough Leather": 180,
            "Cotton Fabric": 180,
            "Cheese Needle": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Rough Leather": 360,
            "Reptile Leather": 360,
            "Cotton Fabric": 360,
            "Linen Fabric": 360,
            "Cheese Needle": 9,
            "Verdant Needle": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Reptile Leather": 1_440,
            "Linen Fabric": 1_440,
            "Verdant Needle": 12,
            "Azure Needle": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Reptile Leather": 1_440,
            "Gobo Leather": 1_440,
            "Linen Fabric": 1_440,
            "Bamboo Fabric": 1_440,
            "Azure Needle": 15,
            "Burble Needle": 15,
            "Tailoring Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Gobo Leather": 5_760,
            "Bamboo Fabric": 5_760,
            "Burble Needle": 18,
            "Crimson Needle": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Gobo Leather": 5_760,
            "Beast Leather": 5_760,
            "Bamboo Fabric": 5_760,
            "Silk Fabric": 5_760,
            "Crimson Needle": 21,
            "Rainbow Needle": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Beast Leather": 11_520,
            "Umbral Leather": 11_520,
            "Silk Fabric": 11_520,
            "Radiant Fabric": 11_520,
            "Rainbow Needle": 24,
            "Holy Needle": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Umbral Leather": 28_800,
            "Radiant Fabric": 28_800,
            "Holy Needle": 60,
            "Super Tailoring Tea": 2_000,
        },
    },
    Kitchen: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            Sugar: 2_000,
            Egg: 500,
            Wheat: 500,
            "Cheese Spatula": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            Sugar: 8_000,
            Egg: 1_000,
            Blueberry: 1_000,
            Wheat: 1_000,
            Apple: 500,
            "Cheese Spatula": 9,
            "Verdant Spatula": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            Sugar: 20_000,
            Blueberry: 2_000,
            Blackberry: 2_000,
            Apple: 1_000,
            Orange: 1_000,
            "Verdant Spatula": 12,
            "Azure Spatula": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            Sugar: 48_000,
            Blackberry: 4_000,
            Strawberry: 4_000,
            Orange: 2_000,
            Plum: 2_000,
            "Azure Spatula": 15,
            "Burble Spatula": 15,
            "Cooking Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            Sugar: 100_000,
            Strawberry: 8_000,
            Mooberry: 8_000,
            Plum: 4_000,
            Peach: 4_000,
            "Burble Spatula": 18,
            "Crimson Spatula": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            Sugar: 200_000,
            Mooberry: 16_000,
            Marsberry: 16_000,
            Peach: 8_000,
            "Dragon Fruit": 8_000,
            "Crimson Spatula": 21,
            "Rainbow Spatula": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            Sugar: 360_000,
            Marsberry: 32_000,
            Spaceberry: 32_000,
            "Dragon Fruit": 16_000,
            "Star Fruit": 16_000,
            "Rainbow Spatula": 24,
            "Holy Spatula": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            Sugar: 640_000,
            Spaceberry: 80_000,
            "Star Fruit": 40_000,
            "Holy Spatula": 60,
            "Super Cooking Tea": 2_000,
        },
    },
    Brewery: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Green Tea Leaf": 300,
            "Arabica Coffee Bean": 300,
            "Cheese Pot": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Green Tea Leaf": 600,
            "Black Tea Leaf": 600,
            "Arabica Coffee Bean": 600,
            "Robusta Coffee Bean": 600,
            "Cheese Pot": 9,
            "Verdant Pot": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Black Tea Leaf": 2_400,
            "Burble Tea Leaf": 2_400,
            "Robusta Coffee Bean": 2_400,
            "Liberica Coffee Bean": 2_400,
            "Verdant Pot": 12,
            "Azure Pot": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Black Tea Leaf": 2_400,
            "Burble Tea Leaf": 2_400,
            "Robusta Coffee Bean": 2_400,
            "Liberica Coffee Bean": 2_400,
            "Azure Pot": 15,
            "Burble Pot": 15,
            "Brewing Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Burble Tea Leaf": 4_800,
            "Moolong Tea Leaf": 4_800,
            "Liberica Coffee Bean": 4_800,
            "Excelsa Coffee Bean": 4_800,
            "Burble Pot": 18,
            "Crimson Pot": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Moolong Tea Leaf": 9_600,
            "Red Tea Leaf": 9_600,
            "Excelsa Coffee Bean": 9_600,
            "Fieriosa Coffee Bean": 9_600,
            "Crimson Pot": 21,
            "Rainbow Pot": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Red Tea Leaf": 19_200,
            "Emp Tea Leaf": 19_200,
            "Fieriosa Coffee Bean": 19_200,
            "Spacia Coffee Bean": 19_200,
            "Rainbow Pot": 24,
            "Holy Pot": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Emp Tea Leaf": 48_000,
            "Spacia Coffee Bean": 48_000,
            "Holy Pot": 60,
            "Super Brewing Tea": 2_000,
        },
    },
    Laboratory: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Milking Essence": 100,
            "Foraging Essence": 100,
            "Woodcutting Essence": 100,
            "Cheese Alembic": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Cheesesmithing Essence": 200,
            "Crafting Essence": 200,
            "Tailoring Essence": 200,
            "Cheese Alembic": 9,
            "Verdant Alembic": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Cooking Essence": 500,
            "Brewing Essence": 500,
            "Verdant Alembic": 12,
            "Azure Alembic": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Alchemy Essence": 1_000,
            "Enhancing Essence": 1_000,
            "Azure Alembic": 15,
            "Burble Alembic": 15,
            "Alchemy Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Milking Essence": 1_600,
            "Foraging Essence": 1_600,
            "Woodcutting Essence": 1_600,
            "Burble Alembic": 18,
            "Crimson Alembic": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Cheesesmithing Essence": 3_200,
            "Crafting Essence": 3_200,
            "Tailoring Essence": 3_200,
            "Crimson Alembic": 21,
            "Rainbow Alembic": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Cooking Essence": 8_000,
            "Brewing Essence": 8_000,
            "Rainbow Alembic": 24,
            "Holy Alembic": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Alchemy Essence": 12_000,
            "Enhancing Essence": 12_000,
            "Holy Alembic": 60,
            "Super Alchemy Tea": 2_000,
        },
    },
    Observatory: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Swamp Essence": 750,
            "Cheese Enhancer": 6,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Swamp Essence": 1_500,
            "Aqua Essence": 1_500,
            "Cheese Enhancer": 9,
            "Verdant Enhancer": 9,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Aqua Essence": 3_000,
            "Jungle Essence": 3_000,
            "Verdant Enhancer": 12,
            "Azure Enhancer": 12,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Jungle Essence": 6_000,
            "Gobo Essence": 6_000,
            "Azure Enhancer": 15,
            "Burble Enhancer": 15,
            "Enhancing Tea": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Gobo Essence": 12_000,
            "Eyessence": 12_000,
            "Burble Enhancer": 18,
            "Crimson Enhancer": 18,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Eyessence": 24_000,
            "Sorcerer Essence": 24_000,
            "Crimson Enhancer": 21,
            "Rainbow Enhancer": 21,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Sorcerer Essence": 48_000,
            "Bear Essence": 48_000,
            "Rainbow Enhancer": 24,
            "Holy Enhancer": 24,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Bear Essence": 120_000,
            "Holy Enhancer": 60,
            "Super Enhancing Tea": 2_000,
        },
    },
    "Dining Room": {
        1: {
            Coin: 500_000,
            Lumber: 75,
            Donut: 125,
            Cupcake: 125,
            "Small Pouch": 1,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            Donut: 250,
            "Blueberry Donut": 250,
            Cupcake: 250,
            "Blueberry Cake": 250,
            "Small Pouch": 3,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Blueberry Donut": 500,
            "Blackberry Donut": 500,
            "Blueberry Cake": 500,
            "Blackberry Cake": 500,
            "Medium Pouch": 1,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Blackberry Donut": 1_000,
            "Strawberry Donut": 1_000, // Strawberry Donut
            "Blackberry Cake": 1_000,
            "Strawberry Cake": 1_000,
            "Medium Pouch": 3,
            "Stamina Coffee": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Strawberry Donut": 2_000,
            "Mooberry Donut": 2_000,
            "Strawberry Cake": 2_000,
            "Mooberry Cake": 2_000,
            "Large Pouch": 1,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Mooberry Donut": 4_000,
            "Marsberry Donut": 4_000,
            "Mooberry Cake": 4_000,
            "Marsberry Cake": 4_000,
            "Large Pouch": 3,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Marsberry Donut": 8_000,
            "Spaceberry Donut": 8_000,
            "Marsberry Cake": 8_000,
            "Spaceberry Cake": 8_000,
            "Giant Pouch": 1,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Spaceberry Donut": 20_000,
            "Spaceberry Cake": 20_000,
            "Giant Pouch": 3,
            "Super Stamina Coffee": 2_000,
        },
    },
    Library: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            Gummy: 250,
            Yogurt: 250,
            Poke: 2,
            Scratch: 2,
            Smack: 2,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            Gummy: 500,
            "Apple Gummy": 250,
            Yogurt: 500,
            "Apple Yogurt": 250,
            "Quick Shot": 2,
            "Water Strike": 2,
            Entangle: 2,
            Fireball: 2,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Apple Gummy": 500,
            "Orange Gummy": 500,
            "Apple Yogurt": 500,
            "Orange Yogurt": 500,
            Toughness: 2,
            Precision: 2,
            Cleave: 2,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Orange Gummy": 1_000,
            "Plum Gummy": 1_000,
            "Orange Yogurt": 1_000,
            "Plum Yogurt": 1_000,
            Impale: 2,
            Sweep: 2,
            "Rain Of Arrows": 2,
            "Ice Spear": 2,
            "Flame Blast": 2,
            "Intelligence Coffee": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Plum Gummy": 2_000,
            "Peach Gummy": 2_000,
            "Plum Yogurt": 2_000,
            "Peach Yogurt": 2_000,
            Berserk: 2,
            Frenzy: 2,
            "Elemental Affinity": 2,
            "Toxic Pollen": 2,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Peach Gummy": 4_000,
            "Dragon Fruit Gummy": 4_000,
            "Peach Yogurt": 4_000,
            "Dragon Fruit Yogurt": 4_000,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Dragon Fruit Gummy": 8_000,
            "Star Fruit Gummy": 8_000,
            "Dragon Fruit Yogurt": 8_000,
            "Star Fruit Yogurt": 8_000,
            Puncture: 2,
            Maim: 2,
            "Stunning Blow": 2,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Star Fruit Gummy": 20_000,
            "Star Fruit Yogurt": 20_000,
            "Silencing Shot": 2,
            "Frost Surge": 2,
            "Nature's Veil": 2,
            Firestorm: 2,
            "Super Intelligence Coffee": 2_000,
        },
    },
    Dojo: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Cheese Spear": 16,
            "Cheese Sword": 12,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Cheese Spear": 24,
            "Verdant Spear": 24,
            "Cheese Sword": 12,
            "Verdant Sword": 12,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Verdant Spear": 32,
            "Azure Spear": 32,
            "Verdant Sword": 16,
            "Azure Sword": 16,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Azure Spear": 40,
            "Burble Spear": 40,
            "Azure Sword": 20,
            "Burble Sword": 20,
            "Attack Coffee": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Burble Spear": 48,
            "Crimson Spear": 48,
            "Burble Sword": 24,
            "Crimson Sword": 24,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Crimson Spear": 56,
            "Rainbow Spear": 56,
            "Crimson Sword": 28,
            "Rainbow Sword": 28,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Rainbow Spear": 64,
            "Holy Spear": 64,
            "Rainbow Sword": 32,
            "Holy Sword": 32,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Holy Spear": 160,
            "Holy Sword": 80,
            "Super Attack Coffee": 2_000,
        },
    },
    Gym: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Cheese Mace": 16,
            "Cheese Sword": 8,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Cheese Mace": 24,
            "Verdant Mace": 24,
            "Cheese Sword": 12,
            "Verdant Sword": 12,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Verdant Mace": 32,
            "Azure Mace": 32,
            "Verdant Sword": 16,
            "Azure Sword": 16,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Azure Mace": 40,
            "Burble Mace": 40,
            "Azure Sword": 20,
            "Burble Sword": 20,
            "Melee Coffee": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Burble Mace": 48,
            "Crimson Mace": 48,
            "Burble Sword": 24,
            "Crimson Sword": 24,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Crimson Mace": 56,
            "Rainbow Mace": 56,
            "Crimson Sword": 28,
            "Rainbow Sword": 28,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Rainbow Mace": 64,
            "Holy Mace": 64,
            "Rainbow Sword": 32,
            "Holy Sword": 32,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Holy Mace": 160,
            "Holy Sword": 80,
            "Super Melee Coffee": 2_000,
        },
    },
    Armory: {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Cheese Helmet": 8,
            "Cheese Plate Body": 8,
            "Cheese Plate Legs": 8,
            "Cheese Gauntlets": 8,
            "Cheese Boots": 8,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Cheese Helmet": 12,
            "Verdant Helmet": 12,
            "Cheese Plate Body": 12,
            "Verdant Plate Body": 12,
            "Cheese Plate Legs": 12,
            "Verdant Plate Legs": 12,
            "Cheese Gauntlets": 12,
            "Verdant Gauntlets": 12,
            "Cheese Boots": 12,
            "Verdant Boots": 12,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Verdant Helmet": 16,
            "Azure Helmet": 16,
            "Verdant Plate Body": 16,
            "Azure Plate Body": 16,
            "Verdant Plate Legs": 16,
            "Azure Plate Legs": 16,
            "Verdant Gauntlets": 16,
            "Azure Gauntlets": 16,
            "Verdant Boots": 16,
            "Azure Boots": 16,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Azure Helmet": 20,
            "Burble Helmet": 20,
            "Azure Plate Body": 20,
            "Burble Plate Body": 20,
            "Azure Plate Legs": 20,
            "Burble Plate Legs": 20,
            "Azure Gauntlets": 20,
            "Burble Gauntlets": 20,
            "Azure Boots": 20,
            "Burble Boots": 20,
            "Defense Coffee": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Burble Helmet": 24,
            "Crimson Helmet": 24,
            "Burble Plate Body": 24,
            "Crimson Plate Body": 24,
            "Burble Plate Legs": 24,
            "Crimson Plate Legs": 24,
            "Burble Gauntlets": 24,
            "Crimson Gauntlets": 24,
            "Burble Boots": 24,
            "Crimson Boots": 24,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Crimson Helmet": 28,
            "Rainbow Helmet": 28,
            "Crimson Plate Body": 28,
            "Rainbow Plate Body": 28,
            "Crimson Plate Legs": 28,
            "Rainbow Plate Legs": 28,
            "Crimson Gauntlets": 28,
            "Rainbow Gauntlets": 28,
            "Crimson Boots": 28,
            "Rainbow Boots": 28,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Rainbow Helmet": 32,
            "Holy Helmet": 32,
            "Rainbow Plate Body": 32,
            "Holy Plate Body": 32,
            "Rainbow Plate Legs": 32,
            "Holy Plate Legs": 32,
            "Rainbow Gauntlets": 32,
            "Holy Gauntlets": 32,
            "Rainbow Boots": 32,
            "Holy Boots": 32,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Holy Helmet": 80,
            "Holy Plate Body": 80,
            "Holy Plate Legs": 80,
            "Holy Gauntlets": 80,
            "Holy Boots": 80,
            "Super Defense Coffee": 2_000,
        },
    },
    "Archery Range": {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Wooden Crossbow": 6,
            "Wooden Bow": 4,
            "Rough Hood": 4,
            "Rough Tunic": 4,
            "Rough Chaps": 4,
            "Rough Bracers": 4,
            "Rough Boots": 4,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Wooden Crossbow": 9,
            "Birch Crossbow": 9,
            "Wooden Bow": 6,
            "Birch Bow": 6,
            "Reptile Hood": 8,
            "Reptile Tunic": 8,
            "Reptile Chaps": 8,
            "Reptile Bracers": 8,
            "Reptile Boots": 8,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Birch Crossbow": 12,
            "Cedar Crossbow": 12,
            "Birch Bow": 8,
            "Cedar Bow": 8,
            "Reptile Hood": 16,
            "Reptile Tunic": 16,
            "Reptile Chaps": 16,
            "Reptile Bracers": 16,
            "Reptile Boots": 16,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Cedar Crossbow": 15,
            "Purpleheart Crossbow": 15,
            "Cedar Bow": 10,
            "Purpleheart Bow": 10,
            "Gobo Hood": 16,
            "Gobo Tunic": 16,
            "Gobo Chaps": 16,
            "Gobo Bracers": 16,
            "Gobo Boots": 16,
            "Ranged Coffee": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Purpleheart Crossbow": 18,
            "Ginkgo Crossbow": 18,
            "Purpleheart Bow": 12,
            "Ginkgo Bow": 12,
            "Gobo Hood": 32,
            "Gobo Tunic": 32,
            "Gobo Chaps": 32,
            "Gobo Bracers": 32,
            "Gobo Boots": 32,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Ginkgo Crossbow": 21,
            "Redwood Crossbow": 21,
            "Ginkgo Bow": 14,
            "Redwood Bow": 14,
            "Beast Hood": 24,
            "Beast Tunic": 24,
            "Beast Chaps": 24,
            "Beast Bracers": 24,
            "Beast Boots": 24,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Redwood Crossbow": 24,
            "Arcane Crossbow": 24,
            "Redwood Bow": 16,
            "Arcane Bow": 16,
            "Beast Hood": 48,
            "Beast Tunic": 48,
            "Beast Chaps": 48,
            "Beast Bracers": 48,
            "Beast Boots": 48,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Arcane Crossbow": 60,
            "Arcane Bow": 40,
            "Umbral Hood": 40,
            "Umbral Tunic": 40,
            "Umbral Chaps": 40,
            "Umbral Bracers": 40,
            "Umbral Boots": 40,
            "Super Ranged Coffee": 2_000,
        },
    },
    "Mystical Study": {
        1: {
            Coin: 500_000,
            Lumber: 75,
            "Wooden Water Staff": 4,
            "Wooden Nature Staff": 4,
            "Wooden Fire Staff": 4,
            "Cotton Hat": 4,
            "Cotton Robe Top": 4,
            "Cotton Robe Bottoms": 4,
            "Cotton Gloves": 4,
            "Cotton Boots": 4,
        },
        2: {
            Coin: 2_000_000,
            Lumber: 150,
            "Birch Lumber": 150,
            "Wooden Water Staff": 6,
            "Wooden Nature Staff": 6,
            "Wooden Fire Staff": 6,
            "Linen Hat": 8,
            "Linen Robe Top": 8,
            "Linen Robe Bottoms": 8,
            "Linen Gloves": 8,
            "Linen Boots": 8,
        },
        3: {
            Coin: 5_000_000,
            "Birch Lumber": 300,
            "Cedar Lumber": 300,
            "Birch Water Staff": 8,
            "Birch Nature Staff": 8,
            "Birch Fire Staff": 8,
            "Linen Hat": 16,
            "Linen Robe Top": 16,
            "Linen Robe Bottoms": 16,
            "Linen Gloves": 16,
            "Linen Boots": 16,
        },
        4: {
            Coin: 12_000_000,
            "Cedar Lumber": 600,
            "Purpleheart Lumber": 600,
            "Cedar Water Staff": 10,
            "Cedar Nature Staff": 10,
            "Cedar Fire Staff": 10,
            "Bamboo Hat": 16,
            "Bamboo Robe Top": 16,
            "Bamboo Robe Bottoms": 16,
            "Bamboo Gloves": 16,
            "Bamboo Boots": 16,
            "Magic Coffee": 1_000,
        },
        5: {
            Coin: 25_000_000,
            "Purpleheart Lumber": 1_200,
            "Ginkgo Lumber": 1_200,
            "Purpleheart Water Staff": 12,
            "Purpleheart Nature Staff": 12,
            "Purpleheart Fire Staff": 12,
            "Bamboo Hat": 32,
            "Bamboo Robe Top": 32,
            "Bamboo Robe Bottoms": 32,
            "Bamboo Gloves": 32,
            "Bamboo Boots": 32,
        },
        6: {
            Coin: 50_000_000,
            "Ginkgo Lumber": 2_400,
            "Redwood Lumber": 2_400,
            "Ginkgo Water Staff": 14,
            "Ginkgo Nature Staff": 14,
            "Ginkgo Fire Staff": 14,
            "Silk Hat": 24,
            "Silk Robe Top": 24,
            "Silk Robe Bottoms": 24,
            "Silk Gloves": 24,
            "Silk Boots": 24,
        },
        7: {
            Coin: 90_000_000,
            "Redwood Lumber": 4_800,
            "Arcane Lumber": 4_800,
            "Redwood Water Staff": 16,
            "Redwood Nature Staff": 16,
            "Redwood Fire Staff": 16,
            "Silk Hat": 48,
            "Silk Robe Top": 48,
            "Silk Robe Bottoms": 48,
            "Silk Gloves": 48,
            "Silk Boots": 48,
        },
        8: {
            Coin: 160_000_000,
            "Arcane Lumber": 12_000,
            "Arcane Water Staff": 40,
            "Arcane Nature Staff": 40,
            "Arcane Fire Staff": 40,
            "Radiant Hat": 40,
            "Radiant Robe Top": 40,
            "Radiant Robe Bottoms": 40,
            "Radiant Gloves": 40,
            "Radiant Boots": 40,
            "Super Magic Coffee": 2_000,
        },
    }
};
