export const MATERIALS = [
    "Coin",
    "Lumber",
    "Birch Lumber",
    "Cedar Lumber",
    "Purpleheart Lumber",
    "Ginkgo Lumber",
    "Redwood Lumber",
    "Arcane Lumber",
    "Milk",
    "Verdant Milk",
    "Azure Milk",
    "Burble Milk",
    "Crimson Milk",
    "Rainbow Milk",
    "Holy Milk",
    "Cheese Brush",
    "Verdant Brush",
    "Azure Brush",
    "Burble Brush",
    "Crimson Brush",
    "Rainbow Brush",
    "Holy Brush",
    "Milking Tea",
    "Super Milking Tea",
    "Egg",
    "Wheat",
    "Cotton",
    "Blueberry",
    "Blackberry",
    "Orange",
    "Apple",
    "Strawberry",
    "Mooberry",
    "Marsberry",
    "Spaceberry",
    "Dragon Fruit",
    "Star Fruit",
    "Plum",
    "Peach",
    "Bamboo Branch",
    "Flax",
    "Cocoon",
    "Radiant Fiber",
    "Cheese Shears",
    "Verdant Shears",
    "Azure Shears",
    "Burble Shears",
    "Crimson Shears",
    "Rainbow Shears",
    "Holy Shears",
    "Foraging Tea",
    "Super Foraging Tea",
    "Log",
    "Birch Log",
    "Cedar Log",
    "Purpleheart Log",
    "Ginkgo Log",
    "Redwood Log",
    "Arcane Log",
    "Cheese Hatchet",
    "Verdant Hatchet",
    "Azure Hatchet",
    "Burble Hatchet",
    "Crimson Hatchet",
    "Rainbow Hatchet",
    "Holy Hatchet",
    "Woodcutting Tea",
    "Super Woodcutting Tea",
    "Cheese",
    "Verdant Cheese",
    "Azure Cheese",
    "Burble Cheese",
    "Crimson Cheese",
    "Rainbow Cheese",
    "Holy Cheese",
    "Cheese Hammer",
    "Verdant Hammer",
    "Azure Hammer",
    "Burble Hammer",
    "Crimson Hammer",
    "Rainbow Hammer",
    "Holy Hammer",
    "Cheesesmithing Tea",
    "Super Cheesesmithing Tea",
    "Cheese Chisel",
    "Verdant Chisel",
    "Azure Chisel",
    "Burble Chisel",
    "Crimson Chisel",
    "Rainbow Chisel",
    "Holy Chisel",
    "Crafting Tea",
    "Super Crafting Tea",
    "Rough Leather",
    "Reptile Leather",
    "Gobo Leather",
    "Beast Leather",
    "Umbral Leather",
    "Cotton Fabric",
    "Linen Fabric",
    "Bamboo Fabric",
    "Silk Fabric",
    "Radiant Fabric",
    "Cheese Needle",
    "Verdant Needle",
    "Azure Needle",
    "Burble Needle",
    "Crimson Needle",
    "Rainbow Needle",
    "Holy Needle",
    "Tailoring Tea",
    "Super Tailoring Tea",
    "Sugar",
    "Cheese Spatula",
    "Verdant Spatula",
    "Azure Spatula",
    "Burble Spatula",
    "Crimson Spatula",
    "Rainbow Spatula",
    "Holy Spatula",
    "Cooking Tea",
    "Super Cooking Tea",
    "Green Tea Leaf",
    "Black Tea Leaf",
    "Burble Tea Leaf",
    "Moolong Tea Leaf",
    "Red Tea Leaf",
    "Emp Tea Leaf",
    "Arabica Coffee Bean",
    "Robusta Coffee Bean",
    "Liberica Coffee Bean",
    "Excelsa Coffee Bean",
    "Fieriosa Coffee Bean",
    "Spacia Coffee Bean",
    "Cheese Pot",
    "Verdant Pot",
    "Azure Pot",
    "Burble Pot",
    "Crimson Pot",
    "Rainbow Pot",
    "Holy Pot",
    "Brewing Tea",
    "Super Brewing Tea",
    "Milking Essence",
    "Foraging Essence",
    "Woodcutting Essence",
    "Cheesesmithing Essence",
    "Crafting Essence",
    "Tailoring Essence",
    "Cooking Essence",
    "Brewing Essence",
    "Alchemy Essence",
    "Enhancing Essence",
    "Cheese Alembic",
    "Verdant Alembic",
    "Azure Alembic",
    "Burble Alembic",
    "Crimson Alembic",
    "Rainbow Alembic",
    "Holy Alembic",
    "Alchemy Tea",
    "Super Alchemy Tea",
    "Swamp Essence",
    "Aqua Essence",
    "Jungle Essence",
    "Gobo Essence",
    "Eyessence",
    "Sorcerer Essence",
    "Bear Essence",
    "Cheese Enhancer",
    "Verdant Enhancer",
    "Azure Enhancer",
    "Burble Enhancer",
    "Crimson Enhancer",
    "Rainbow Enhancer",
    "Holy Enhancer",
    "Enhancing Tea",
    "Super Enhancing Tea",
    "Donut",
    "Blueberry Donut",
    "Blackberry Donut",
    "Strawberry Donut",
    "Mooberry Donut",
    "Marsberry Donut",
    "Spaceberry Donut",
    "Cupcake",
    "Blueberry Cake",
    "Blackberry Cake",
    "Strawberry Cake",
    "Mooberry Cake",
    "Marsberry Cake",
    "Spaceberry Cake",
    "Small Pouch",
    "Medium Pouch",
    "Large Pouch",
    "Giant Pouch",
    "Stamina Coffee",
    "Super Stamina Coffee",
    "Gummy",
    "Apple Gummy",
    "Orange Gummy",
    "Plum Gummy",
    "Peach Gummy",
    "Dragon Fruit Gummy",
    "Star Fruit Gummy",
    "Yogurt",
    "Apple Yogurt",
    "Orange Yogurt",
    "Plum Yogurt",
    "Peach Yogurt",
    "Dragon Fruit Yogurt",
    "Star Fruit Yogurt",
    "Poke",
    "Scratch",
    "Smack",
    "Quick Shot",
    "Water Strike",
    "Entangle",
    "Fireball",
    "Toughness",
    "Precision",
    "Impale",
    "Cleave",
    "Sweep",
    "Rain Of Arrows",
    "Ice Spear",
    "Flame Blast",
    "Toxic Pollen",
    "Berserk",
    "Frenzy",
    "Elemental Affinity",
    "Puncture",
    "Maim",
    "Stunning Blow",
    "Silencing Shot",
    "Frost Surge",
    "Nature's Veil",
    "Firestorm",
    "Intelligence Coffee",
    "Super Intelligence Coffee",
    "Cheese Spear",
    "Verdant Spear",
    "Azure Spear",
    "Burble Spear",
    "Crimson Spear",
    "Rainbow Spear",
    "Holy Spear",
    "Cheese Sword",
    "Verdant Sword",
    "Azure Sword",
    "Burble Sword",
    "Crimson Sword",
    "Rainbow Sword",
    "Holy Sword",
    "Attack Coffee",
    "Super Attack Coffee",
    "Cheese Mace",
    "Verdant Mace",
    "Azure Mace",
    "Burble Mace",
    "Crimson Mace",
    "Rainbow Mace",
    "Holy Mace",
    "Melee Coffee",
    "Super Melee Coffee",
    "Cheese Helmet",
    "Verdant Helmet",
    "Azure Helmet",
    "Burble Helmet",
    "Crimson Helmet",
    "Rainbow Helmet",
    "Holy Helmet",
    "Cheese Plate Body",
    "Verdant Plate Body",
    "Azure Plate Body",
    "Burble Plate Body",
    "Crimson Plate Body",
    "Rainbow Plate Body",
    "Holy Plate Body",
    "Cheese Plate Legs",
    "Verdant Plate Legs",
    "Azure Plate Legs",
    "Burble Plate Legs",
    "Crimson Plate Legs",
    "Rainbow Plate Legs",
    "Holy Plate Legs",
    "Cheese Gauntlets",
    "Verdant Gauntlets",
    "Azure Gauntlets",
    "Burble Gauntlets",
    "Crimson Gauntlets",
    "Rainbow Gauntlets",
    "Holy Gauntlets",
    "Cheese Boots",
    "Verdant Boots",
    "Azure Boots",
    "Burble Boots",
    "Crimson Boots",
    "Rainbow Boots",
    "Holy Boots",
    "Defense Coffee",
    "Super Defense Coffee",
    "Wooden Crossbow",
    "Birch Crossbow",
    "Cedar Crossbow",
    "Purpleheart Crossbow",
    "Ginkgo Crossbow",
    "Redwood Crossbow",
    "Arcane Crossbow",
    "Wooden Bow",
    "Birch Bow",
    "Cedar Bow",
    "Purpleheart Bow",
    "Ginkgo Bow",
    "Redwood Bow",
    "Arcane Bow",
    "Rough Hood",
    "Rough Tunic",
    "Rough Chaps",
    "Rough Bracers",
    "Rough Boots",
    "Reptile Hood",
    "Reptile Tunic",
    "Reptile Chaps",
    "Reptile Bracers",
    "Reptile Boots",
    "Gobo Hood",
    "Gobo Tunic",
    "Gobo Chaps",
    "Gobo Bracers",
    "Gobo Boots",
    "Beast Hood",
    "Beast Tunic",
    "Beast Chaps",
    "Beast Bracers",
    "Beast Boots",
    "Umbral Hood",
    "Umbral Tunic",
    "Umbral Chaps",
    "Umbral Bracers",
    "Umbral Boots",
    "Ranged Coffee",
    "Super Ranged Coffee",
    "Wooden Water Staff",
    "Birch Water Staff",
    "Cedar Water Staff",
    "Purpleheart Water Staff",
    "Ginkgo Water Staff",
    "Redwood Water Staff",
    "Arcane Water Staff",
    "Wooden Nature Staff",
    "Birch Nature Staff",
    "Cedar Nature Staff",
    "Purpleheart Nature Staff",
    "Ginkgo Nature Staff",
    "Redwood Nature Staff",
    "Arcane Nature Staff",
    "Wooden Fire Staff",
    "Birch Fire Staff",
    "Cedar Fire Staff",
    "Purpleheart Fire Staff",
    "Ginkgo Fire Staff",
    "Redwood Fire Staff",
    "Arcane Fire Staff",
    "Cotton Hat",
    "Cotton Robe Top",
    "Cotton Robe Bottoms",
    "Cotton Gloves",
    "Cotton Boots",
    "Linen Hat",
    "Linen Robe Top",
    "Linen Robe Bottoms",
    "Linen Gloves",
    "Linen Boots",
    "Bamboo Hat",
    "Bamboo Robe Top",
    "Bamboo Robe Bottoms",
    "Bamboo Gloves",
    "Bamboo Boots",
    "Silk Hat",
    "Silk Robe Top",
    "Silk Robe Bottoms",
    "Silk Gloves",
    "Silk Boots",
    "Radiant Hat",
    "Radiant Robe Top",
    "Radiant Robe Bottoms",
    "Radiant Gloves",
    "Radiant Boots",
    "Magic Coffee",
    "Super Magic Coffee"
] as const;

export type MaterialId = (typeof MATERIALS)[number];
